# Generated by Django 6.1 on 2026-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
